services:
  db:
    image: postgres:16
    container_name: project-management-system-db
    environment:
      POSTGRES_DB: project-management
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pm-data:/var/lib/prostgresql/data
  db-ui:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=enaunay@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - db-ui-data:/var/lib/pgadmin
    ports:
      - "8085:80"
  api:
    build: .
    container_name: project-management-system
    environment:
      - REPO_BACKEND=postgres
      - DB_URL=postgresql://root:root@db:5432/project-management
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  pm-data:
  db-ui-data:
  