services:
  api:
    build: .
    container_name: project-management-system
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1 # Avoid writing __pycache__ files
    restart: unless-stopped
